### PR TITLE
Add typo3/cms-dashboard as required package

### PR DESCRIPTION
**Pull request by sascha-egerer**

### CODE REVIEW

**Comment by froemken** [comment]
Hello @sascha-egerer 

I really like the dashboard extension, but there are more people out there who don't like the dashboard extension. I can't make both groups happy. In the early days I already had a requirement of dashboard which I have removed again, because of "useless dashboard ext in LIVE systems".
I searched a long time and found a solution to add widgets only, if EXT dashboard is available:
https://github.com/froemken/mysqlreport/blob/main/Classes/DependencyInjection/DashboardPass.php

So, for now I will not add this requirement again.

Thank you for your support

Stefan

**Comment by sascha-egerer** [comment]
@froemken Well the problem was that the extension did use Classes that are provided by the dashboard extension. I tried to install this extension and it failed when building the services container.

```
 [ Symfony\Component\DependencyInjection\Exception\RuntimeException ]
  Invalid service "dashboard.widget.mysql-max-used-connections": class "TYPO3\CMS\Dashboard\Widgets\DoughnutChartWidget" does not exist.
```

**Comment by sascha-egerer** [comment]
@froemken Ah i just found #97 and wondered why i still have that problem. Then i noticed that i'm not on the latest version as is required TYPO3 11.5.33 and i'm on a somehow older version containing manual security patches. Is there any reason for the .33 requirement?

**Comment by froemken** [comment]
Hello @sascha-egerer 

with each ext update I also update the dependency for typo3/cms-core:
https://packagist.org/packages/typo3/cms-core

I always update it to the latest stable secure version.

Stefan

**Comment by sascha-egerer** [comment]
> Hello @sascha-egerer
> 
> with each ext update I also update the dependency for typo3/cms-core: https://packagist.org/packages/typo3/cms-core
> 
> I always update it to the latest stable secure version.
> 
> Stefan

Yeah this happens quite often and IMO this isn't a good pattern if there is real requirement. So i would suggest to not limit bugfix versions at all in the future if not really necessary. But anyways lets stop here. I'll postpone the installation of the extension.

**Pull request closed without merging**
